apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:4318
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: jaeger
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: \[.+,(.+?),
          name: TraceID
          url: $${__value.raw}