server:
  port: 8080
spring:
  application:
    name: events-service
  cloud:
    consul:
      host: consul
      port: 8500
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  # send traces to zipkin instance as well to view them not just in grafana
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}