server:
  port: 8081
spring:
  application:
    name: events-service
  cloud:
    consul:
      host: localhost
      port: 8500
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}