version: "3"
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  events-service:
    build:
      context: ./events-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - redis

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - redis

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - consul
      - redis

  pricing-service:
    build:
      context: ./pricing-service
      dockerfile: Dockerfile
    ports:
      - "8283:8283"
    depends_on:
      - consul
      - redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9412:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.74.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55680:55680"
      - "9411:9411"
      - "9464:9464"
      - "8888:8888"
    depends_on:
      - jaeger
      - zipkin

  prometheus:
    image: prom/prometheus:v2.43.0
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./otel/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.2.15
    volumes:
      - ./otel/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./otel/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
