version: "3"
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  events-service:
    build:
      context: ./events-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - redis

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - redis

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - consul
      - redis

  pricing-service:
    build:
      context: ./pricing-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - consul
      - redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
