version: "3"
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  events-service:
    build:
      context: ./events-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - redis

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - redis

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - consul
      - redis

  pricing-service:
    build:
      context: ./pricing-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - consul
      - redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  loki:
    image: grafana/loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  grafana:
    image: grafana/grafana
    volumes:
      - ./otel/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./otel/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
