server:
  port: 8081
spring:
  application:
    name: booking-service
  cloud:
    consul:
      host: consul
      port: 8500
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}