server:
  port: 8081
spring:
  application:
    name: booking-service
  cloud:
    consul:
      host: consul
      port: 8500

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://jaeger:4318/v1/traces

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'