server:
  port: 8082
spring:
  application:
    name: payment-service
  cloud:
    consul:
      host: localhost
      port: 8500
management:
  health:
    db:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        exclude: health

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}